### ISSUE TITLE
Update to FFTW v1.0

### ISSUE THREAD

**Issue by oschulz** [JuliaDSP/Deconvolution.jl#6]
Deconvolution is currently blocking updates of FFTW (now at v1.0.1).

**Comment by giordano** [comment]
Thank you so much for the report!  I think I only needed to add the `Project.toml` file, this package still had the `REQUIRE` only.  A new version should be tagged in a few minutes: https://github.com/JuliaRegistries/General/pull/5048

**Comment by oschulz** [comment]
Thanks for the super-quick fix, Mosè!
