### ISSUE TITLE
Use Documenter.jl for the documentation

### ISSUE THREAD

**Issue by giordano** [JuliaDSP/Deconvolution.jl#9]
We should use https://github.com/JuliaDocs/Documenter.jl for the documentation

**Comment by jakubwro** [comment]
This week I have time to work on this. Can I take the task?

**Comment by giordano** [comment]
Wow, thanks for volunteering. Actually my idea was for a Google code in student to take this, so maybe let's see first if any of them is willing to do this task 😉

**Comment by jakubwro** [comment]
Sure :)
